 


#There are two list structures explicitly supported by CPP:
* token list
* argument list

A tokens are gotten from the lexer, hence the token list is a data structure. Each token has a type, such as identifier or punctuation.

An argument list is a common separated list of token lists.  Though sometimes special requirements are made, such that a list member be single token, or a single token of identifier type.

#Operations to support list structures

* _TO_ARG_LIST( <token_list> )
* _TO_TOKEN_LIST( <arg_list> )

#Token List operators

* _FIRST( <token_list> )
* _REST( <token_list> )
* _MAP( f ,<token_ilst> )
* _AL_MAP( f ,<argument_ilst> )

`_FIRST` and `_REST` expand as expected. 

`_MAP` expands as `f(token) ...`
`_AL_MAP` expands to `f(arg) ...`

We also add:

* _IF( p ,a ,b)

_IF can be implemented with #define. However, we still provide a built-in version.

If `p` exists, expands to `a`, otherwise expands to `b`.  Any of the arguments can be missing, in which case they are taken to be false.  Note,

We build this in:

* _NOT( p )

Which is the same as:

```
#define NOT(x) _IF(x ,,TRUE)
```

If `p` is a token, a token list, or an argument list, `_NOT( p )` expands to nothing. Otherwise it expands to `TRUE`. This is the only operator among those discussed here that introduces a token not already found among its inputs. Here `TRUE` is a non-identifying statement of existence.

As false is the absence of anything, logical connectors such as AND and OR can not be defined for token lists.  However, they can be defined for argument lists, as argument lists can represent the absence of an argument.  Hence we have built-in:

* _AND( <argument_list> )
* _OR( <argument_list> )

`_AND` expands to nothing if there are any absent members of the argument list. There is an interesting end case however, a missing last member will not be detected.  A programmer can append TRUE to the end of a list to avoid this effect.

`_OR` expands to the first argument that is present in the argument list.  If there is no first argument, then it expands to nothing. There is no problem with missing argument off the end of the list.

#Paste connects tokens to create a single token.

Only Identifier tokens can be pasted. Giving a non-identifer token results the error:

```
paste_1.c:9:46: error: pasting "x" and "y" does not give a valid preprocessing token
```

The CPP paste operator is found between tokens. There is no operator for pasting all the tokens in a list.  So we add:

* _PASTE( <token_list> )

#Token operators

* _IS_IDENTIFIER( <arg> )

If <arg> is an argument list, or a tokens list, or the token is not an identifier, expands to nothing.  Otherwise expands to the given identifier.

#Set

```
#define _SET_ADD(set ,x) ASSIGN( _PASTE( __SET_ ,set ,_ ,x), )
```

```
#define _SET_IN(set ,x)  _NOT(_PASTE( __SET_ ,set ,_ ,x))
```

If the member is in the set, expands to TRUE, otherwise expands to nothing.

#ASet


```
#assign _ASET_ADD(set ,x ,y) (
  ASSIGN( _PASTE( __ASET_ ,set ,_ ,x ))
  ASSIGN( _PASTE( __ASET_ITEM_ ,set ,_ ,x))
  )
```

```
#assign  _ASET_GET(set ,x) (
   _IF(
        _PASTE( __ASET_ ,set ,_ ,x)
        , _PASTE( __ASET_ITEM ,set ,_ ,x)
        ,
        )
```


#List

```
#define _LIST_CONNECT(list ,node ,x) ASSIGN( _PASTE( __LIST_ ,list ,_ ,x), )
#define _LIST_NEXT(list ,x) ASSIGN( _PASTE( __LIST_ ,list ,_ ,x), )
```
