#!/bin/bash
set -euo pipefail

source "$(dirname "$0")/environment.sh"

echo "📦 Checking prerequisites for glibc..."

required_tools=(gcc make curl tar perl python3 gawk bison)
missing_tools=()

for tool in "${required_tools[@]}"; do
  if ! command -v "$tool" > /dev/null; then
    missing_tools+=("$tool")
  fi
done

if (( ${#missing_tools[@]} )); then
  echo "❌ Missing required tools:"
  printf '   %s\n' "${missing_tools[@]}"
  exit 1
fi

# Check that expected headers exist
glibc_headers=(
  "$SYSROOT/usr/include/stdio.h"
  "$SYSROOT/usr/include/unistd.h"
)

# Check that expected startup objects exist
startup_objects=(
  "$SYSROOT/usr/lib/crt1.o"
  "$SYSROOT/usr/lib/crti.o"
  "$SYSROOT/usr/lib/crtn.o"
)

missing_files=()
for f in "${glibc_headers[@]}" "${startup_objects[@]}"; do
  if [ ! -f "$f" ]; then
    missing_files+=("$f")
  fi
done

if (( ${#missing_files[@]} )); then
  echo "❌ Missing required files in sysroot:"
  printf '   %s\n' "${missing_files[@]}"
  echo
  echo "Hint: these files should have been generated by build_glibc_headers.sh"
  exit 1
fi

echo "✅ All prerequisites for glibc are met and sysroot is correctly populated."
