
* cpp_ext

The cpp_ext.c files will work with gcc without the RT extensions.  With the RT extensions they are deprecated.

** cpp_ext_0

The cpp_ext_0 implements logic and sets, and does not use recursion. It is a little different than other cpp logic files because it is based on absence being false, and existence being true. Hence '0' would be true, as it exists. It provides a BOOLEAN macro for converting to 0 and 1 logic.  

cpp_ext_0 does not make use of tricky recursion techniques, nor does it make use of the RT cpp extensions.

** cpp_ext_1

This is an example of what not to do with production code.  This is not part of the RT extensions.  

However, cpp_ext_1 is wonderful way to learn more about cpp.  It tricks cpp into doing limited depth recursion despite its macro painting feature.

It did make it into some of my C code for implementing variadic CAT before it was available without recursion with the RT extensions.

I pulled the original version from Jonathan Heathcote's "cpp magic", http://jhnet.co.uk/articles/cpp_magic, and modified it to work with the non-existence is false logic.  Open AI suggests additional contributors to cpp trickery:

    Paul F. Dubois — wrote about C macro tricks in early numerical computing contexts.

    Laurent Deniau — author of The C Preprocessor as a Turing-complete language.

    Joachim Durchholz, Pavel Vozenilek, Walter Bright, and others — contributed deep macro insights in forums like comp.lang.c.

    The Boost Preprocessor Library (by Paul Mensonides and others) contains some of the most extensive and formalized C macro "magic" ever crafted.

Using cpp_ext_1 can result in very long error messages when compiling. Get some popcorn, and have fun watching them scroll by.

* cpp_ext_rt

In cpp_ext_0 it was not possible to write a routine that adds a member to a set, because cpp had no facilitate for auto-generating  macro names.  The `#assign` directive in the rt extension solves this problem.

CAT is an often used macro for prefixing a namespace, prefixing a set name to the front of an identifier before a membership test, or creating identifiers for equality matching.  Seldom do we need very many arguments for these use case, though the exact number is not always bounded.

Variadic CAT seems like a reasonable thing to be able to do. One might imagine putting ## in front of __VA_ARGS__; though it would be nice to also have an optional separator. Hence, I added the built in macro RT_CAT(SEP, ...).


