* General Notes

GNU `cpp` is integrated with the GNU gcc repo.

There is a lot more to GCC than one might imagine. It was developed as though an integral part of Unix. Hence, the standalone build has top-level directories that resemble the top level of a Unix system.

The scripts here will download source and build a standalone GCC 12 along with version-compatible tools.


* RT extensions

If you want the RT extensions, the RT extension sources must be copied from library/ after the gcc sources are expanded. Use `RT_extensions_install.sh`. When editing the sources, generally the library/ versions are treated as authoritive.

* environment

Don't forget `source env_toolsmith` in your shell.

* Setup

- `setup_project.sh` :: Makes the directory structure for the build, creates a `tmp/` directory under the project. If it does not already exist, creates a `.gitignore` file with all the created directories listed.

* Top level .gitignore

- There is no `.gitignore` at the top level when the project is cloned. The `.gitignore` created by `setup_project.sh` ignores itself, so it will not be checked in.
- No script deletes the top level `.gitignore`, including the clean scripts, so the toolsmith can make edits there that persist locally.

* Clean

- `clean_build.sh` :: For saving space after the build is done. The build scripts are idempotent, so in an ideal world this need not be run to do a rebuild.

- `clean_dist.sh` :: With one exception, this will delete everything that was synthesized. The one exception is that `.gitignore` is moved to the `tmp/` directory to preserve any changes a user might have made, and the contents of the `tmp/` directory are not removed.

- `clean_tmp.sh` :: Wipes clean all contents of the temporary directory.

* Download

- `download_upstream_sources.sh` :: Goes to the Internet, fetches all the sources that have not already been fetched. Then expands the sources into the proper sub-directory under `source/1`.

* Build

See the script build_all.sh for a description of the complete build process.

When editing the RT Extensions, the work flow is typically:

while cwd in the script directory:
1. edit the library/<file.cc>
2. `./RT_extension_install.h`
3. `./rebuild_gcc.sh`
4. run some experiments

It would of course be better to have a test suite.

I typically leave an emacs shell open in the $ROOT/source/gcc-12.2.0/libcpp/ directory for purposes of exploring the other source code files.     
